version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: DB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=online-payments-secret
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  be:
    container_name: BE
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app/online-payments
volumes:
  mongo-db:
