version: "3"
services:
  be:
    build: .
    container_name: BE
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: DB
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=online-payments-secret
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
